const mongoose = require('mongoose');

const Schema = mongoose.Schema;


const sponsorSchema = new Schema({
    //id is autogenerated
    linkedin_id : { type: String, required: true },
    first_name : { type: String, required: true },
    last_name : { type: String, required: true },
    avatar : { type: String, required: true },
    email: { type: String, required: true },
    business: { type: String, required: false },
    title: { type: String, required: false },
})

module.exports = mongoose.model('Sponsor', sponsorSchema);