const mongoose = require('mongoose');

const Schema = mongoose.Schema;

const DUMMY_SPONSOR_SUBMISSION = [
    {
    'id' : 's1',
    't_job_titles' : ['j1', 'j2'],
    't_industry' : ['i1', 'i2'],
    't_client_list' : 'test.csv',
    't_employee_count': 50,
    't_users': ['u1', 'u3'],
    'date_start': 'Feb 1st 2021',
    'date_end' : 'Feb 1st 2021',
    't_topic' : 0,
    't_host' : 0
    }
];

const sponsorRequestSchema = new Schema({
    //id is autogenerated
    jobTitles: { type: Array, "default": [] }, 
    industries: { type: Array, "default": [] }, 
    clientList: { type: String, required: false}, 
    headCounts: { type: Array, "default": [] },
    regions: { type: Array, "default": [] }, 
    users: { type: Array, "default": [] }, 
    dates: { type: Array, required: true},
    topic: { type: Boolean, "default": 0}, 
    host: { type: Boolean, "default": 0},
    sponsor: { type: String, required: false}
});

module.exports = mongoose.model('SponsorRequest', sponsorRequestSchema);