//About: jobtitles colection is where Fuzzy logic user search happens
const mongoose = require('mongoose');

const Schema = mongoose.Schema;

const DUMMY_USER_SEARCH = [
    {
        titles : ['Chief Information Officer'],
        industry : ['Financial Services'],
        employees : '50',
        regions : ['west', 'south-west']
    }
];

const targetUsersSchema = new Schema({
    //id is autogenerated
    "First Name" : { type: String, required: false },
    "Last Name" : { type: String, required: false },
    Position : { type: String, required: false },
    "Personal Description" : { type: String, required: false},
    Experience : { type: String, required: false},
    City : { type: String, required: false},
    State : { type: String, required: false},
    Education : { type: String, required: false},
    Company : { type: String, required: false},
    "# of Employees" : { type: String, required: false},
    "Estimated Revenues" : { type: String, required: false},
    Industry: { type: String, required: false},
    "Personal Photo": { type: String, required: false},
    "LinkedIn URL": { type: String, required: false}
});

module.exports = mongoose.model('TargetUsers', targetUsersSchema);